server:
  port: 8082

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:26257/account_db?sslmode=disable
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  flyway:
    schemas:
      locations: classpath:db/migration/cockroach